// Procedural closed-loop track generator.
//
// SECTION-BASED design: the track is anchored by ~10 control points
// arranged around the origin. The path BETWEEN each pair of consecutive
// anchors is generated by one of several "strategies" — straight,
// bezier sweep, snake-game zigzag, 45° diagonal kink, chicane, or
// sweeping curve — picked per segment based on its length and a coin
// flip. The result feels hand-built: long straights, big bezier
// sweepers, tight snake stretches, all in one lap.
//
// All distances are in METRES.

import { mulberry32, rfloat } from './rng.js';

// ---------------------------------------------------------------------------
//   Section strategies — each returns the intermediate points between
//   anchors a and b (NOT including a or b; those are anchored). Strategies
//   are pure functions of (a, b, rng) and never touch shared state.
// ---------------------------------------------------------------------------

// STRAIGHT — just a midpoint so the closed loop has something to smooth.
function straightStrat(a, b, rng) {
  return [{ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }];
}
straightStrat.kind = 'straight';

// LONG STRAIGHTAWAY — a few intermediate points along the line for top-speed
// runs. The renderer's resample handles dash spacing so we don't need many.
function straightawayStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const steps = 4;
  const pts = [];
  for (let i = 1; i < steps; i++) {
    const t = i / steps;
    pts.push({ x: a.x + dx * t, y: a.y + dy * t });
  }
  return pts;
}
straightawayStrat.kind = 'straightaway';

// BEZIER SWEEP — wide cubic Bezier curve with both control handles offset
// to the same side, giving a long flowing arc.
function bezierSweepStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const len = Math.hypot(dx, dy) || 1;
  const px = -dy / len, py = dx / len;
  const offMul = rfloat(rng, 0.25, 0.50);
  const off = (rng() < 0.5 ? 1 : -1) * len * offMul;
  const c1 = { x: a.x + dx * 0.33 + px * off, y: a.y + dy * 0.33 + py * off };
  const c2 = { x: a.x + dx * 0.67 + px * off, y: a.y + dy * 0.67 + py * off };
  const steps = Math.max(8, Math.floor(len / 4));
  const pts = [];
  for (let i = 1; i < steps; i++) {
    const t = i / steps;
    const mt = 1 - t;
    pts.push({
      x: mt*mt*mt*a.x + 3*mt*mt*t*c1.x + 3*mt*t*t*c2.x + t*t*t*b.x,
      y: mt*mt*mt*a.y + 3*mt*mt*t*c1.y + 3*mt*t*t*c2.y + t*t*t*b.y,
    });
  }
  return pts;
}
bezierSweepStrat.kind = 'bezier';

// SNAKE — game-of-snake style: axis-aligned segments (in the section's local
// frame) with sharp 90° turns. After the global Chaikin smoothing pass these
// read as a tight wiggling section with crisp-ish corners.
function snakeStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const len = Math.hypot(dx, dy) || 1;
  const fx = dx / len, fy = dy / len;
  const px = -fy, py = fx;
  const zigs = 2 + Math.floor(rng() * 3);    // 2-4 zigs
  const amp = Math.min(len * 0.16, 14);
  const pts = [];
  for (let i = 1; i <= zigs * 2; i++) {
    const t = i / (zigs * 2 + 1);
    const sgn = ((i - 1) % 2 === 0) ? 1 : -1;
    pts.push({
      x: a.x + fx * len * t + px * amp * sgn,
      y: a.y + fy * len * t + py * amp * sgn,
    });
  }
  return pts;
}
snakeStrat.kind = 'snake';

// 45° DIAGONAL CONNECTOR — sidesteps perpendicular for a bit, then comes
// back. Reads as two visible ~45° kinks at either end of the section.
function diagonalKinkStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const len = Math.hypot(dx, dy) || 1;
  const fx = dx / len, fy = dy / len;
  const px = -fy, py = fx;
  const off = len * rfloat(rng, 0.16, 0.25);
  const sgn = rng() < 0.5 ? 1 : -1;
  return [
    { x: a.x + fx * len * 0.3 + px * off * sgn, y: a.y + fy * len * 0.3 + py * off * sgn },
    { x: a.x + fx * len * 0.7 + px * off * sgn, y: a.y + fy * len * 0.7 + py * off * sgn },
  ];
}
diagonalKinkStrat.kind = 'diagonal';

// CHICANE — short S-curve through the middle. One offset to one side,
// then the opposite. Great for technical sections.
function chicaneStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const len = Math.hypot(dx, dy) || 1;
  const fx = dx / len, fy = dy / len;
  const px = -fy, py = fx;
  const amp = len * 0.22;
  const sgn = rng() < 0.5 ? 1 : -1;
  return [
    { x: a.x + fx * len * 0.25 + px * amp * sgn, y: a.y + fy * len * 0.25 + py * amp * sgn },
    { x: a.x + fx * len * 0.50,                  y: a.y + fy * len * 0.50 },
    { x: a.x + fx * len * 0.75 - px * amp * sgn, y: a.y + fy * len * 0.75 - py * amp * sgn },
  ];
}
chicaneStrat.kind = 'chicane';

// HAIRPIN — heavy single-side offset with two control points close together
// in the local-Y axis. After smoothing this looks like a fat U-turn that
// pushes well outside the straight-line a→b path.
function hairpinStrat(a, b, rng) {
  const dx = b.x - a.x, dy = b.y - a.y;
  const len = Math.hypot(dx, dy) || 1;
  const fx = dx / len, fy = dy / len;
  const px = -fy, py = fx;
  const amp = len * rfloat(rng, 0.45, 0.75);
  const sgn = rng() < 0.5 ? 1 : -1;
  return [
    { x: a.x + fx * len * 0.18 + px * amp * 0.6 * sgn, y: a.y + fy * len * 0.18 + py * amp * 0.6 * sgn },
    { x: a.x + fx * len * 0.45 + px * amp       * sgn, y: a.y + fy * len * 0.45 + py * amp       * sgn },
    { x: a.x + fx * len * 0.55 + px * amp       * sgn, y: a.y + fy * len * 0.55 + py * amp       * sgn },
    { x: a.x + fx * len * 0.82 + px * amp * 0.6 * sgn, y: a.y + fy * len * 0.82 + py * amp * 0.6 * sgn },
  ];
}
hairpinStrat.kind = 'hairpin';

// Pick a strategy weighted by segment length. Short segments favour
// straights/snakes; medium ones favour everything; long ones favour
// sweeping bezier curves and snakes.
function pickStrategy(segLen, rng) {
  const r = rng();
  if (segLen < 25) {
    if (r < 0.55) return straightStrat;
    if (r < 0.85) return snakeStrat;
    return diagonalKinkStrat;
  }
  if (segLen < 55) {
    if (r < 0.25) return bezierSweepStrat;
    if (r < 0.45) return chicaneStrat;
    if (r < 0.65) return diagonalKinkStrat;
    if (r < 0.82) return snakeStrat;
    if (r < 0.92) return hairpinStrat;
    return straightawayStrat;
  }
  // Long segment.
  if (r < 0.35) return bezierSweepStrat;
  if (r < 0.55) return straightawayStrat;
  if (r < 0.72) return snakeStrat;
  if (r < 0.88) return chicaneStrat;
  return hairpinStrat;
}

// ---------------------------------------------------------------------------
//   Centerline assembly
// ---------------------------------------------------------------------------

export function generateTrack(seed) {
  const rng = mulberry32(seed >>> 0);

  // Anchor polygon — 9-12 points roughly on a circle with some radial and
  // angular jitter. The strategy decoration between consecutive anchors is
  // what gives the track its character.
  const N = 9 + Math.floor(rng() * 4);
  const baseR = 95;
  const radJitter = 28;
  const angularJitter = 0.16;
  const anchors = [];
  for (let i = 0; i < N; i++) {
    const a = (i / N) * Math.PI * 2 + rfloat(rng, -angularJitter, angularJitter);
    const r = baseR + rfloat(rng, -radJitter, radJitter);
    anchors.push({ x: Math.cos(a) * r, y: Math.sin(a) * r });
  }

  // Decorate each segment between consecutive anchors.
  const ctrl = [];
  const strategyKinds = [];
  for (let i = 0; i < N; i++) {
    const a = anchors[i];
    const b = anchors[(i + 1) % N];
    ctrl.push(a);
    const segLen = Math.hypot(b.x - a.x, b.y - a.y);
    const strat = pickStrategy(segLen, rng);
    strategyKinds.push(strat.kind);
    const inter = strat(a, b, rng);
    for (const p of inter) ctrl.push(p);
  }

  // One Chaikin pass smooths strategy boundaries without melting the
  // distinctive shapes (snake corners, hairpin tightness).
  let pts = chaikinClosed(ctrl);

  // Resample at 3m so the edge ring is smooth.
  pts = resampleByArc(pts, 3);

  // Track width — 24m base, ±4m. Wide enough for arcade racing.
  const widthBase = 24;
  const widthVar  = 4;
  const widthPhase = rng() * Math.PI * 2;
  const widthFreq = 3 + Math.floor(rng() * 3);
  const widths = pts.map((_, i) => {
    const t = (i / pts.length) * Math.PI * 2;
    return widthBase + Math.sin(t * widthFreq + widthPhase) * widthVar;
  });
  // Pit lane near start/finish stays ≥ 28m so the 4-wide grid fits.
  const startMin = 28;
  const startRange = 14;
  for (let i = 0; i < startRange; i++) {
    const idxBack = (pts.length - i) % pts.length;
    widths[i] = Math.max(widths[i], startMin);
    widths[idxBack] = Math.max(widths[idxBack], startMin);
  }

  const start = pts[0];
  const startTangent = normalize({
    x: pts[1].x - pts[pts.length - 1].x,
    y: pts[1].y - pts[pts.length - 1].y,
  });
  const startNormal = { x: -startTangent.y, y: startTangent.x };
  const startWidth = widths[0];

  // Checkpoints — evenly spaced along the loop, used for lap detection.
  const numCheckpoints = 8;
  const step = Math.floor(pts.length / numCheckpoints);
  const checkpoints = [];
  for (let i = 0; i < numCheckpoints; i++) {
    const idx = (i * step) % pts.length;
    const cp = pts[idx];
    const prev = pts[(idx - 1 + pts.length) % pts.length];
    const next = pts[(idx + 1) % pts.length];
    const tx = next.x - prev.x;
    const ty = next.y - prev.y;
    const len = Math.hypot(tx, ty) || 1;
    const nx = -ty / len, ny = tx / len;
    const w = widths[idx] / 2;
    checkpoints.push({
      cx: cp.x, cy: cp.y,
      ax: cp.x + nx * w, ay: cp.y + ny * w,
      bx: cp.x - nx * w, by: cp.y - ny * w,
      index: idx,
    });
  }

  // Pickup slots — every ~75 m of track, alternating sides.
  const pickupSlots = [];
  const pickupStep = 25;
  for (let i = 0; i < pts.length; i += pickupStep) {
    const p = pts[i];
    const prev = pts[(i - 1 + pts.length) % pts.length];
    const next = pts[(i + 1) % pts.length];
    const tx = next.x - prev.x;
    const ty = next.y - prev.y;
    const len = Math.hypot(tx, ty) || 1;
    const nx = -ty / len, ny = tx / len;
    const off = widths[i] * 0.22 * ((i % (pickupStep * 2) === 0) ? 1 : -1);
    pickupSlots.push({ x: p.x + nx * off, y: p.y + ny * off });
  }

  // CSG tiles for physics-side track containment (clampToTrack).
  const tiles = [];
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    const dx = b.x - a.x, dy = b.y - a.y;
    const len = Math.hypot(dx, dy) || 1;
    const ux = dx / len, uy = dy / len;
    const nx = -uy, ny = ux;
    const wA = widths[i] / 2;
    const wB = widths[(i + 1) % widths.length] / 2;
    tiles.push({
      al: { x: a.x + nx * wA, y: a.y + ny * wA },
      ar: { x: a.x - nx * wA, y: a.y - ny * wA },
      bl: { x: b.x + nx * wB, y: b.y + ny * wB },
      br: { x: b.x - nx * wB, y: b.y - ny * wB },
      ax: a.x, ay: a.y, bx: b.x, by: b.y,
      ux, uy, nx, ny,
      len, wA, wB,
    });
  }

  // Legacy inner/outer (used only by the minimap). Computed cheaply.
  const inner = [], outer = [];
  for (let i = 0; i < pts.length; i++) {
    const t = tiles[i];
    inner.push({ x: t.al.x, y: t.al.y });
    outer.push({ x: t.ar.x, y: t.ar.y });
  }

  // World bounds.
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const t of tiles) {
    for (const c of [t.al, t.ar, t.bl, t.br]) {
      if (c.x < minX) minX = c.x;
      if (c.y < minY) minY = c.y;
      if (c.x > maxX) maxX = c.x;
      if (c.y > maxY) maxY = c.y;
    }
  }
  const pad = 12;
  const bounds = {
    minX: minX - pad, minY: minY - pad,
    maxX: maxX + pad, maxY: maxY + pad,
  };

  return {
    seed,
    centerline: pts,
    widths,
    tiles,
    inner,
    outer,
    strategies: strategyKinds,
    start: {
      x: start.x, y: start.y,
      tx: startTangent.x, ty: startTangent.y,
      nx: startNormal.x, ny: startNormal.y,
      width: startWidth,
    },
    checkpoints,
    pickupSlots,
    bounds,
  };
}

// ---------------------------------------------------------------------------
//   Maths helpers
// ---------------------------------------------------------------------------

function chaikinClosed(pts) {
  const out = [];
  const n = pts.length;
  for (let i = 0; i < n; i++) {
    const p = pts[i];
    const q = pts[(i + 1) % n];
    out.push({ x: 0.75 * p.x + 0.25 * q.x, y: 0.75 * p.y + 0.25 * q.y });
    out.push({ x: 0.25 * p.x + 0.75 * q.x, y: 0.25 * p.y + 0.75 * q.y });
  }
  return out;
}

function resampleByArc(pts, spacing) {
  const out = [];
  let acc = 0;
  out.push(pts[0]);
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    const dx = b.x - a.x, dy = b.y - a.y;
    const seg = Math.hypot(dx, dy);
    let t = 0;
    while (acc + seg - t >= spacing) {
      const need = spacing - acc;
      t += need;
      acc = 0;
      const u = t / seg;
      out.push({ x: a.x + dx * u, y: a.y + dy * u });
    }
    acc += seg - t;
  }
  return out;
}

function normalize(v) {
  const l = Math.hypot(v.x, v.y) || 1;
  return { x: v.x / l, y: v.y / l };
}

// Grid 4-wide × N-deep, all behind the start line. Lateral span is 10.5m
// (4 columns at 3.5m spacing); fits inside the guaranteed ≥28m pit lane.
export function gridSpawnPositions(track, count) {
  const { start } = track;
  const slots = [];
  const COLS = 4;
  const colSpacing = 3.5;
  const rowSpacing = 6;
  const colOffset = -(COLS - 1) / 2;
  for (let i = 0; i < count; i++) {
    const colIdx = i % COLS;
    const rowIdx = Math.floor(i / COLS);
    const back = -rowSpacing * (rowIdx + 1);
    const side = (colOffset + colIdx) * colSpacing;
    const x = start.x + start.tx * back + start.nx * side;
    const y = start.y + start.ty * back + start.ny * side;
    const angle = Math.atan2(start.ty, start.tx);
    slots.push({ x, y, angle });
  }
  return slots;
}
